apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: quay-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/quay/quay-rhel8-operator-catalog:1.1.0-6
